version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mcallejo3
      MYSQL_DATABASE: events-mvp-back
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
